services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    # group_add:
    #   - ${DOCKER_GROUP_ID}
    restart: always

volumes:
  jenkins_home: